export enum PassErrorCodes {
  NOT_FOUND = 'PASS_NOT_FOUND',
  WALLET_NOT_FOUND = 'PASS_WALLET_NOT_FOUND',
  ALREADY_USED = 'PASS_ALREADY_USED',
  NO_USES_LEFT = 'NO_USES_LEFT',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  COUPON_ALREADY_USED = 'COUPON_ALREADY_USED',
  COUPON_EXPIRED = 'COUPON_EXPIRED',
  NOT_COMPLETED = 'PASS_NOT_COMPLETED',
}
